europe = [
    "Bulgaria", 
    "Albania", 
    "Austria",
    "Belarus", 
    "Belgium",
    "Bosnia and Herzegovina", 
    "Croatia", 
    "Cyprus", 
    "Czech Republic", 
    "Czechoslovakia",
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France",
    "Germany", 
    "Greece", 
    "Hungary", 
    "Iceland", 
    "Ireland", 
    "Italy", 
    "Latvia",
    "Lithuania",
    "Luxembourg", 
    "Macedonia", 
    "Malta", 
    "Moldova",
    "Montenegro", 
    "Netherlands",
    "Norway",
    "Poland", 
    "Portugal", 
    "Romania", 
    "Russia", 
    "Serbia", 
    "Serbia and Montenegro",
    "Slovakia", 
    "Slovenia", 
    "Spain", 
    "Sweden",
    "Switzerland",
    "Turkey", 
    "Ukraine",
    "United Kingdom", 
    "USSR"
]

north_america = [
    "Canada", 
    "Mexico", 
    "United States"
]

south_america = [
    "Brazil", 
    "Argentina", 
    "Bolivia", 
    "Chile",
    "Colombia",
    "Ecuador", 
    "Guyana", 
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay", 
    "Venezuela"
]

carribean_central_america = [
    "Costa Rica", 
    "Antigua and Barbuda", 
    "Bahamas", 
    "Barbados", 
    "Belize", 
    "Bermuda", 
    "Cuba", 
    "Dominica",
    "Dominican Republic",
    "El Salvador", 
    "Grenada",
    "Guatemala",
    "Haiti", 
    "Honduras", 
    "Jamaica",
    "Nicaragua",
    "Panama",
    "Saint Kitts and Nevis", 
    "Saint Lucia", 
    "Saint Vincent and the Grenadines", 
    "Trinidad and Tobago"
]

asia = [
    "Brunei",
    "Afghanistan", 
    "Armenia",
    "Azerbaijan", 
    "Bangladesh",
    "Cambodia", 
    "China", 
    "Georgia",
    "India", 
    "Indonesia",
    "Iran",
    "Iraq", 
    "Israel", 
    "Japan", 
    "Jordan",
    "Kazakhstan",
    "Kuwait",
    "Kyrgyzstan",
    "Laos", 
    "Lebanon", 
    "Malaysia",
    "Maldives", 
    "Mongolia", 
    "Myanmar", 
    "Nepal",
    "North Korea",
    "Oman", 
    "Pakistan",
    "Philippines", 
    "Saudi Arabia",
    "South Korea", 
    "Sri Lanka", 
    "Tajikistan",
    "Thailand", 
    "Turkmenistan",
    "United Arab Emirates",
    "Uzbekistan",
    "Vietnam", 
    "Yemen"
]

africa = [
    "Botswana", 
    "Algeria",
    "Angola", 
    "Benin", 
    "Burkina Faso",
    "Cabo Verde", 
    "Cameroon", 
    "Central African Republic",
    "Chad", 
    "Congo", 
    "Cote d'Ivoire",
    "Djibouti",
    "Egypt", 
    "Ethiopia",
    "Gabon", 
    "Gambia", 
    "Ghana", 
    "Guinea",
    "Guinea-Bissau", 
    "Kenya", 
    "Lesotho", 
    "Liberia", 
    "Madagascar",
    "Malawi", 
    "Mali", 
    "Mauritania", 
    "Mauritius", 
    "Morocco", 
    "Mozambique",
    "Namibia",
    "Niger", 
    "Nigeria", 
    "Rwanda", 
    "Sao Tome and Principe", 
    "Senegal", 
    "Sierra Leone", 
    "South Africa", 
    "Sudan", 
    "Swaziland", 
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia", 
    "Zimbabwe"
]

oceania =  [
    "Australia",
    "Fiji", 
    "French Polynesia",
    "Kiribati",
    "New Caledonia",
    "New Zealand", 
    "Samoa",
    "Solomon Islands", 
    "Vanuatu"
]

continents = [
    "Europe", 
    "North America",
    "South America",
    "Caribbean and Central America", 
    "Asia", 
    "Africa", 
    "Oceania"
]

diet_columns = [
    "cereals_grains",
    "pulses", 
    "starchy_roots",
    "sugar", 
    "oils_fats",
    "meat", 
    "dairy_eggs", 
    "fruit_veg",
    "other", 
    "alcohol"
]